In [1]:
import pandas as pd

In [2]:
csv_fname = 'res_csv/rep_small.csv'
pd_rep_small = pd.read_csv(csv_fname) 

csv_fname = 'res_csv/rep_med.csv'
pd_rep_med = pd.read_csv(csv_fname)

csv_fname = 'res_csv/rep_large.csv'
pd_rep_large = pd.read_csv(csv_fname)

csv_fname = 'res_csv/jes_small.csv'
pd_jes_small = pd.read_csv(csv_fname)

csv_fname = 'res_csv/jes_med.csv'
pd_jes_med = pd.read_csv(csv_fname)

csv_fname = 'res_csv/jes_large.csv'
pd_jes_large = pd.read_csv(csv_fname)

In [3]:
pd_rep_small

     time  memory
0   0.006    2156
1   0.012    2468
2   0.009    2452
3   0.010    2536
4   0.012    2204
5   0.013    2504
6   0.011    2420
7   0.009    2476
8   0.009    2156
9   0.011    2196
10  0.009    2468
11  0.009    2156
12  0.011    2180
13  0.008    2504
14  0.011    2156
15  0.009    2504
16  0.007    2240
17  0.005    2468
18  0.005    2240
19  0.005    2452
20  0.005    2420
21  0.005    2236
22  0.006    2492
23  0.005    2240
24  0.004    2504
25  0.006    2504
26  0.005    2492
27  0.005    2420
28  0.004    2476
29  0.005    2504
..    ...     ...
70  0.006    2504
71  0.005    2204
72  0.004    2468
73  0.006    2452
74  0.013    2196
75  0.005    2420
76  0.005    2416
77  0.005    2204
78  0.005    2428
79  0.005    2424
80  0.005    2504
81  0.004    2156
82  0.006    2156
83  0.006    2180
84  0.005    2420
85  0.005    2540
86  0.008    2460
87  0.004    2156
88  0.005    2460
89  0.006    2180
90  0.005    2424
91  0.005    2448
92  0.007    2424
93  0.005    2156
94  0.005    2476
95  0.006    2448
96  0.005    2488
97  0.004    2460
98  0.005    2156
99  0.006    2456

[100 rows x 2 columns]